version: "3.9"
services:
  db:
    image: postgres:15
    container_name: literature_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: literature
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  search:
    image: opensearchproject/opensearch:2.11.1
    container_name: literature_search
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -s http://localhost:9200 | grep 'opensearch' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  db_data:


